apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: app-${USER}-ingress
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ( $http_test ) {
        set $service_name "app-${USER}-service-blue"
      }  
spec:
  rules:
  - host: ${USER}.cicdworkshop.ezylinux.com
    http:
      paths:
      - backend:
          serviceName: app-${USER}-service-green
          servicePort: 80      
  - host: ${USER}-blue.cicdworkshop.ezylinux.com
    http:
      paths:
      - backend:
          serviceName: app-${USER}-service-blue
          servicePort: 80  
  - host: ${USER}-green.cicdworkshop.ezylinux.com
    http:
      paths:
      - backend:
          serviceName: app-${USER}-service-green
          servicePort: 80      
